### ISSUE TITLE
Conflict with AzuAreaRepair

### ISSUE THREAD

**Issue by FractusNine** [JereKuusela/valheim-infinity_tools#2]
Ran into a potential conflict with AzuAreaRepair --
1. Pick up a connected structure using Building Pipette tool 
2. Put away hammer (somehow this step causes an error, if the hammer isn't put away it doesn't cause an error for me)
3. When trying to place any next piece, the hammer seems to break and throws this error:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
WearNTear.Awake () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
Player:DMD<Player::PlacePiece>(Player, Piece)
Player:DMD<Player::UpdatePlacement>(Player, Boolean, Single)
Player:DMD<Player::Update>(Player)

**Comment by JereKuusela** [comment]
I tried this but couldn't get the issue happen. Are the mods on latest versions?

**Comment by FractusNine** [comment]
Oh hmm, I must be missing something! Mods are on the latest version. I just created a new profile in R2ModMan with just these mods and ran into the same error:
BepinEx
Server_devcommands
World_edit_commands
Infinity_Hammer
Infinity_Tools
AzuAreaRepair

Here is a video of the steps -- looks like I may have forgotten the step of placing the connected piece first. Once that is done, the next pieces place visually, but do not work right. They do not have snap points and disappear when reloading the world. Kept accidentally running into this error when moving around some blueprints. Thanks for looking at this!

https://github.com/JereKuusela/valheim-infinity_tools/assets/82234381/0e3c97c9-b65e-423f-9b2d-8843f35b3bdb

**Comment by JereKuusela** [comment]
Thanks for the video!

Latest update should fix this issue. Let me know if it doesn't.

**Comment by FractusNine** [comment]
That did the trick -- thank you Jere!
