### ISSUE TITLE
Tools do not rotate without modifers and sloap tool does not rotate at all

### ISSUE THREAD

**Issue by Kiaos** [JereKuusela/valheim-infinity_tools#3]
Normally when the mod worked as normal rotation happened when you mouse wheel and then you could hold shift to change size if you wanted to change the size. That no longer works. Now rotating the shape is disabled and it defualts to changing size. Right now by default it is set to change size. and not rotate.  So now i cant position the shape in a direction which makes creating roads imposble.

Broken in 1.4 as well.

**Comment by JereKuusela** [comment]
Ctrl + left shift still allows you to rotate. Of course you can modify the tools to disable terrainGrid if you don't want to use it.

Another option is to copy Slope tool and change the command to `terrain paint=paved <to>` so it paves instead.

**Comment by Kiaos** [comment]
Here is the problem with that. You can only rotate that one way, with mousewheel up or down it always rotates counter clockwise either way. 

   Im gonna be honest changing rotate as you have makes it inoperable with controller and does not feel natural. I wish I could just have an option to change it back to the way it was before and change shift + ctrl to some to player height or some other setting. The way it is now is very clunky. Its better to allow us to change the hold modifiers ourself in config. Allowing the default to rotate with no modifier and holding shift changes size is how the game works normally and making shift ctrl for other things seems better than the way you have made it now. 

Plus i dont think making the modifiers static is aproprate. Please allow us to use a drop down setting for controlers and keyboard. So i can change the modifer for each setting seprately. better yet make a seperate mod to remap the modfiers for this and any rotate tool like comfy gizmo with controller support.

I am using mouse and keyboard for most of my gameplay. But I also use my steam deck so this tool. When I play on steam deck the tool feels mostly usless. I dont enjoy holding two modifers to rotate. When it required no modifers before. It is not just sloap thats the problem but level an the other tools. The sloap tool itself cant rotate and its locked right now as you have it. You have to switch to level roate that and switch back to sloap that is not very intuitive.

**Comment by Kiaos** [comment]
better yet make a seperate mod to remap the modfiers for this and any rotate tool like comfy gizmo

**Comment by Kiaos** [comment]
also you dont need to do the modifers anyway becuase you can assign freemode with cycle snapping e or q bounds  and the text can pop up on the screen saying you can change to free mode or snap so left control is unnessisary if you use q and e to change between snapping and free mode like it is with the other tools. 

P.S. i spent like 1 hour editing because im not very clear when writing so please reread what i posted so its more clear.

**Comment by Kiaos** [comment]
Let take back a few things I checked the config and there is a means to change the modifiers but using configuration manager I have no idea how to change the default mousewheel rotate to roate the shape without modifers. It still doesnt change the fact that you can only rotate counter clockwise using level and that this is disabled in sloap tool. Also here is another bug when you hold left control and shift and let go the roation resets. So you cant use it anyway.

**Comment by JereKuusela** [comment]
On the infinity_tools.yaml, you can remove all "terrainGrid: -<mod2>" from the file.

![image](https://github.com/JereKuusela/valheim-infinity_tools/assets/23279671/67f8eb06-e1f6-4615-b4a2-77d46719d1f7)
should work for changing the rotate as you like. At least will work on the version I will upload later today.

**Comment by Kiaos** [comment]
ok ill try it thank you.

**Comment by JereKuusela** [comment]
![image](https://github.com/JereKuusela/valheim-infinity_tools/assets/23279671/e5ab3857-403a-494d-93d5-c193c00e1703)
You can also try putting some unused bind to Command Rotation. If no bind is valid, it should use the default mouse wheel behavior.

**Comment by Kiaos** [comment]
Thank you.

**Comment by Kiaos** [comment]
were you able to fix the rotation only going counter clock wise? I cant mouse wheel the oposite way and get the oposite rotation.

**Comment by Kiaos** [comment]
#[https://youtu.be/AOOIz3FYXfg](url)

**Comment by Kiaos** [comment]
Ok i removed terrainGrid and now the rotation works but the mousewheel only goes counter clockwise weather i mousewheel up or down.

**Comment by Kiaos** [comment]
You can pin this for others or close it the rotation counter clockwise was fixed with infinity hammer update. Plus I deleted the terrain in the ymal and it works now how i expect it to work. Thank you for your help and good luck with your other projects.

**Comment by Kiaos** [comment]
You can pin this for others or close it. The rotation counter clockwise was fixed with infinity hammer update. Plus I deleted the terrain in the ymal and it works now how i expect it to work. Thank you for your help and good luck with your other projects.
